apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: stu-python-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: "true"
    app.kubernetes.io/part-of: stu-python-app
spec:
  params:
  - name: ports
    value:
    - port: 80
      containerPort: 8000 # gunicorn default port
      name: http
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: testing_pipeline_matching_labels
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: python
  source:
    git:
      url: your-registry.io/project
      ref:
        branch: main
  build:
    env:
      - name: BP_CPYTHON_VERSION
        value: "3.11.4"
